version: '3'

services:
  gitlab-runner:
    build: .
    image: nouchka/gitlab-runner
    hostname: "nouchka-runner"
    environment:
      - REGISTERED_TOKENS=aaaaaaabbbbbbbbbbcccccccc
      - DOCKER_IMAGE=nouchka/symfony:5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
